app = 'montree-shop-list-api-backend'
primary_region = 'gru'

[env]
  PORT = '3333'
  HOST = '0.0.0.0'
  NODE_ENV = 'production'
  LOG_LEVEL = 'info'
  TZ = 'UTC'
  GITHUB_API_URL = 'https://api.github.com/users'
  LIMITER_STORE = 'database'

[[mounts]]
  source = 'data'
  destination = '/app/tmp'

[http_service]
  internal_port = 3333
  force_https = true

[[http_service.checks]]
  interval = '10s'
  timeout = '2s'
  method = 'get'
  path = '/itens'

[[vm]]
  size = 'shared-cpu-1x'
