/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Compras: () => import('#controllers/compras_controller'),
  Itens: () => import('#controllers/itens_controller'),
}
