/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class CompraSchema extends BaseModel {
  static $columns = ['compradorGithubLogin', 'createdAt', 'id', 'itemId', 'updatedAt'] as const
  $columns = CompraSchema.$columns
  @column()
  declare compradorGithubLogin: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ItenSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'nome', 'preco', 'qtdAtual', 'updatedAt'] as const
  $columns = ItenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nome: string
  @column()
  declare preco: number
  @column()
  declare qtdAtual: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}
